### ISSUE TITLE
Error while reading ukwac w2v data

### ISSUE THREAD

**Issue by tezer** [tudarmstadt-lt/sensegram#10]
Doing this:
`import sensegram
sv = sensegram.SenseGram.load_word2vec_format('/home/myHome/Data/word2vec/sensegram/ukwac.senses.w2v', binary=True)`

Gives me that:
```
Traceback (most recent call last):
  File "/home/myHome/PycharmProjects/sensegram/my_progs/prog1.py", line 2, in <module>
    sv = sensegram.SenseGram.load_word2vec_format('/home/myHome/Data/word2vec/sensegram/ukwac.senses.w2v', binary=True)
  File "/home/myHome/PycharmProjects/sensegram/sensegram.py", line 45, in load_word2vec_format
    mod = word2vec.Word2Vec.load_word2vec_format(fname, fvocab, binary, encoding, unicode_errors)
  File "/home/myHome/virtualenv/sensegram/local/lib/python2.7/site-packages/gensim/models/word2vec.py", line 1212, in load_word2vec_format
    weights = fromstring(fin.read(binary_len), dtype=REAL)
ValueError: string size must be a multiple of element size
```
wiki data loaded without any problem

**Comment by alexanderpanchenko** [comment]
cannot reproduce: be sure that you have the correct versions of the libraries eg gensim.

you can run `pip install -r requirements.txt` to make sure you have it

![image](https://user-images.githubusercontent.com/1456830/28543810-56d27c94-70c1-11e7-885d-bcc1caf06906.png)

![image](https://user-images.githubusercontent.com/1456830/28543896-aea49f24-70c1-11e7-856c-8a2b71c6e436.png)

**Comment by tezer** [comment]
Sorry, the problem was on my side: data corruption while downloading
