### ISSUE TITLE
Bug report: the '-pooling_method' switch actually not supported for training

### ISSUE THREAD

**Issue by kaihuchen** [tudarmstadt-lt/sensegram#14]
The README indicates that there is a  '-pooling_method' switch that can be specified for training, but in reality it is not supported in the code.

**Comment by alexanderpanchenko** [comment]
thank you for reporting this issue. we are preparing a new release which will address this issues and will also make certain improvements.

**Comment by alexanderpanchenko** [comment]
resolved in the new release
