### ISSUE TITLE
while training i floor_rise in graph creation. later it failed with scipy error 

### ISSUE THREAD

**Issue by tiru1930** [tudarmstadt-lt/sensegram#17]
OverflowError: Python int too large to convert to C long

Bad line: Floor_rise	Floor_rise	-340282346638528859811704183484516925440.000000

    raise ValueError('row, column, and data array must all be the '
ValueError: row, column, and data array must all be the same length

**Comment by tiru1930** [comment]
Hello

I have just  trained the model with text8 -- i.e make train , it  trained
well, When i try the same with custom data its giving the above error.

Custom data  is having new line and empty lines too. where as text8 is
having all the content in single line.


Regards
Tiru

**Comment by tiru1930** [comment]
python train.py  ../data/my_data.txt
in data file contains all the content in single line.

Traceback (most recent call last):
  File "/home/tiru/Desktop/topicmodel/kul/sensegram/graph.py", line 51, in _load
    data_lst.append(np.int16(floor(float(weight) * WEIGHT_COEF)))
OverflowError: Python int too large to convert to C long

Bad line: floor_rise	floor_rise	-340282346638528859811704183484516925440.000000

Traceback (most recent call last):
  File "/home/tiru/Desktop/topicmodel/kul/sensegram/graph.py", line 51, in _load
    data_lst.append(np.int16(floor(float(weight) * WEIGHT_COEF)))
OverflowError: Python int too large to convert to C long

Bad line: floor_rise	floor_rise	-340282346638528859811704183484516925440.000000

Traceback (most recent call last):
  File "train.py", line 112, in <module>
    main()
  File "train.py", line 84, in main
    word_sense_induction(neighbours_fpath, clusters_fpath, args.n, args.threads)
  File "train.py", line 33, in word_sense_induction
    ego_network_clustering(neighbours_fpath, clusters_fpath, max_related=n, num_cores=threads)
  File "/home/tiru/Desktop/topicmodel/kul/sensegram/word_sense_induction.py", line 55, in ego_network_clustering
    G = CRSGraph(neighbors_fpath)
  File "/home/tiru/Desktop/topicmodel/kul/sensegram/graph.py", line 15, in __init__
    self._graph, self.index = self._load(neighbors_fpath) 
  File "/home/tiru/Desktop/topicmodel/kul/sensegram/graph.py", line 59, in _load
    graph = csr_matrix( (data, (rows, cols)), shape=(len(index),len(index)), dtype=np.int16 )       
  File "/home/tiru/anaconda/lib/python3.6/site-packages/scipy/sparse/compressed.py", line 51, in __init__
    other = self.__class__(coo_matrix(arg1, shape=shape))
  File "/home/tiru/anaconda/lib/python3.6/site-packages/scipy/sparse/coo.py", line 184, in __init__
    self._check()
  File "/home/tiru/anaconda/lib/python3.6/site-packages/scipy/sparse/coo.py", line 228, in _check
    if self.nnz > 0:
  File "/home/tiru/anaconda/lib/python3.6/site-packages/scipy/sparse/base.py", line 201, in nnz
    return self.getnnz()
  File "/home/tiru/anaconda/lib/python3.6/site-packages/scipy/sparse/coo.py", line 190, in getnnz
    raise ValueError('row, column, and data array must all be the '
ValueError: row, column, and data array must all be the same length

**Comment by alexanderpanchenko** [comment]
can you please send me a link to the file you use for training?

**Comment by tiru1930** [comment]
I can't share the data. Is it necessary to have huge data 100MB , to train this

**Comment by alexanderpanchenko** [comment]
maybe you can compress and put it on a dropbox / google drive?

**Comment by tiru1930** [comment]
Sorry , it is not about keeping it google drive, that data what ever i am using is confidential , i can't share outside.

**Comment by alexanderpanchenko** [comment]
ok, i totally see the point, no problem.

1) having everything in a single line is not needed (you can check it by
training the model on wikipedia (the makefile has actually such a command
as well))

2) please provide some information about your file - otherwise it is
difficult to suggest something (encoding, language, etc)

**Comment by tiru1930** [comment]
it is utf-8 encoded and English language,and when i start training it got created .word_vectors files which is having 189 words  with 300 dim, it also create .graph file in which most of the place i am seeing 

36982 Floor_rise      hi      0.305934
36983 Floor_rise      a_Pune  0.087366
36984 Floor_rise      b_Mumbai        0.008943
36985 Floor_rise      Floor_rise      -340282346638528859811704183484516925440.000000
36986 Floor_rise      Floor_rise      -340282346638528859811704183484516925440.000000
36987 Floor_rise      Floor_rise      -340282346638528859811704183484516925440.000000
36988 Floor_rise      Floor_rise      -340282346638528859811704183484516925440.000000
36989 Floor_rise      Floor_rise      -340282346638528859811704183484516925440.000000
36990 Floor_rise      Floor_rise      -340282346638528859811704183484516925440.000000
36991 Floor_rise      Floor_rise      -340282346638528859811704183484516925440.000000
36992 Floor_rise      Floor_rise      -340282346638528859811704183484516925440.000000
36993 Floor_rise      Floor_rise      -340282346638528859811704183484516925440.000000
36994 Floor_rise      Floor_rise      -340282346638528859811704183484516925440.000000
36995 Floor_rise      Floor_rise      -340282346638528859811704183484516925440.000000
36996 Floor_rise      Floor_rise      -340282346638528859811704183484516925440.000000
36997 Floor_rise      Floor_rise      -340282346638528859811704183484516925440.000000
36998 Floor_rise      Floor_rise      -340282346638528859811704183484516925440.000000
36999 Floor_rise      Floor_rise      -340282346638528859811704183484516925440.000000
37000 Floor_rise      Floor_rise      -340282346638528859811704183484516925440.000000

**Comment by alexanderpanchenko** [comment]
please let me know

1) if .word_vectors file is correct or not (you can load it with gensim and
compute nearest neighbours and they make sense)

2) the computational settings (i suspect you issue is with the Facebook
FAISS library)

**Comment by tiru1930** [comment]
in this function while getting neighbours 

def compute_neighbours(index, w2v, nns_fpath, neighbors=200):
    tic = time()
    with codecs.open(nns_fpath, "w", "utf-8") as output:
        X = w2v.syn0norm
        D, I = index.search(X, neighbors + 1)



        j = 0
        for _D, _I in zip(D, I):
            for n, (d, i) in enumerate(zip(_D.ravel(), _I.ravel())):
                if n > 0:
                    if d<0:
                        print(d)
                        print(_D)
                        print(_I)
                    output.write("{}\t{}\t{:f}\n".format(w2v.index2word[j], w2v.index2word[i], d))
            j += 1

        print("Word graph:", nns_fpath)
        print("Elapsed: {:f} sec.".format(time() - tic))

for some words value of d is -3.40282e+38, it is causing the issue.

**Comment by alexanderpanchenko** [comment]
right, this is exactly the part that uses the FAISS library of Facebook.
it is quite trickly to build it correctly (see their website). in the
makefile i provide commands to install it correctly for ubuntu 16.04. for
other platforms you may need to figure out yourself which changes to make
to install it correctly. the library uses lots of binary dependencies, but
unfort. has no python-only alternatives.

**Comment by tiru1930** [comment]
Yes, after struggling so much i am able to install that faiss. have done few changes in make file , i am using gnome ubuntu 16.04.

**Comment by alexanderpanchenko** [comment]
yes, it may be not straighforward. did you try the
```make install-ubuntu-16-04```?

https://github.com/tudarmstadt-lt/sensegram/blob/master/Makefile#L10

i tested it on a clean ubuntu 16.04 server and it just worked fine

**Comment by tiru1930** [comment]
Yes I tried with make install Ubuntu 16.04

**Comment by alexanderpanchenko** [comment]
ok. in this case it would be great to know which were the problems and the
workarounds for future users as well.

**Comment by tiru1930** [comment]
In FAISS make file .. have to specify   c++11 flag and CFLAGS . Which are
mentioned some place in make file ..
