### ISSUE TITLE
Only one Cluster is Created after training. How can we increase these clusters?

### ISSUE THREAD

**Issue by tiru1930** [tudarmstadt-lt/sensegram#18]
Hi 
I am to Train this with custom data, but after completion of training , total number of Clusters created is Only One. I have with increasing the number of nodes also tried by decreasing the same, but total number of cluster are always single. Is there any way to tune or produce more clusters

**Comment by alexanderpanchenko** [comment]
Hello,

Do you get the single cluster per all words or some of the words actually
have more than one?
Currently in WSD various capitalizations are mixed: e.g. 'Apple' can have
one sense (company) and 'apple' can have only one sense (fruit) but in
total these are two candidate senses during the WSD.

**Comment by alexanderpanchenko** [comment]
When training is finished the total number of words and senses are printed. This information would be helpful to figure out what can be the issue.

**Comment by tiru1930** [comment]
Sparse: False
Type of vector normalization: sum
Weight type: score
Max. number of cluster words to use: 20
Sense dim. number (sparse only): 1000
Save pickle (sparse only): False
0 (0) senses loaded of 817
0 cluster errors
817 senses loaded out of 817
738 words loaded

**Comment by alexanderpanchenko** [comment]
can you also report number of lines in the output files

e.g. with wc -l * in the model directory

**Comment by alexanderpanchenko** [comment]
Our method has a tendency to create a new sense only if (1) sense distributions are comparable for two senses; (2) the semantics of the sense is very different (i.e. we speak about homonymy as opposed to polesemy). Besides, as can be observed by the number of words, your corpus is also quite small, which can be also one of the reasons of this result. 

You can try AdaGram sense embeddings which from my experience tend to discover more senses on average (though they may be more overlapping than those of our model).
