### ISSUE TITLE
Does training the model requires context of a word too?

### ISSUE THREAD

**Issue by Abhishek-IIT007** [tudarmstadt-lt/sensegram#19]
I was training this model on 500words and 500 most similar word of each word. i.e. 250000 total words.
I picked those words and their vectors randomly from a pre-trained word2vec file. And i was getting only one sense for each word. So does the  training depends on context of word too? Cause i was getting satisfactory results when training on a corpus.

**Comment by alexanderpanchenko** [comment]
could you please share the code you exactly try to run or commands - it is difficult to understand otherwise it and reproduce the error.

**Comment by Abhishek-IIT007** [comment]
I just used the command 
python train.py model/word_embedd.txt
I wasn't getting any error . the code was running well but the results weren't satisfactory.
word_embedd.txt contained randomly chosen 250000 words and their vectors, not generated from any corpus but chosen randomly from pre trained vector space.
When I  trained it on word embeddings generated from a corpus ,it gave very good results. 
So i wanted to if the sentences/context is also needed to get good results.
