### ISSUE TITLE
Incorrect make file

### ISSUE THREAD

**Issue by gecube** [tudarmstadt-lt/sensegram#22]
https://github.com/tudarmstadt-lt/sensegram/blob/8b13b8f6a40f273f948ca53623a1a7616d8a000d/Makefile#L26

Please fix tabs and spaces, because `make` utility writes that there is error in 26 line.

Also it is very pity that only Ubuntu 16 distribution is supported. I will be glad to see alpine and ubuntu 18 support, because I am planning to incapsulate this great project into docker container

**Comment by alexanderpanchenko** [comment]
I fixed the tab issue. Please note that now faiss can be installed using conda, therefore there is no strict dependency on Ubunty 16.04. If you can install anaconda 3 then the system should run.
