### ISSUE TITLE
Implement context filtering strategy: not all words from the context are useful

### ISSUE THREAD

**Issue by alexanderpanchenko** [tudarmstadt-lt/sensegram#3]

**Comment by mpelevina** [comment]
My idea was to disregard stop words. Do you agree?
For now I can't imagine anything else, but I haven't got yet through the literature, there might be other ideas.

**Comment by alexanderpanchenko** [comment]
Yes, stopwords is a good start. There are couple of other strategies. This is not urgent issue, let us discuss offline.
