### ISSUE TITLE
load_word2vec_format Deprecated

### ISSUE THREAD

**Issue by lmascarell** [tudarmstadt-lt/sensegram#6]
classmethod load_word2vec_format(fname, fvocab=None, binary=False, encoding='utf8', unicode_errors='strict', limit=None, datatype=<type 'numpy.float32'>)
Deprecated. Use gensim.models.KeyedVectors.load_word2vec_format instead.

**Comment by alexanderpanchenko** [comment]
Thank you for this report: We are preparing an updated version where this
is fixed. Currently, you need to use a gensim version prior to 1.0 to be
able to use the tool:

https://github.com/tudarmstadt-lt/sensegram/blob/master/requirements.txt
