### ISSUE TITLE
Pretrained models are not available

### ISSUE THREAD

**Issue by tezer** [tudarmstadt-lt/sensegram#8]
Hi, it seems that your site with pretrained models is down. Is it possible to get them anywhere else, please?

**Comment by alexanderpanchenko** [comment]
This is due to a planned maintenance of the servers. it shall be available
on Tuesday and we will make a mirror to avoid such problems later. Sorry!

**Comment by alexanderpanchenko** [comment]
should work now

**Comment by tezer** [comment]
thank you!
