### ISSUE TITLE
TWSI 

### ISSUE THREAD

**Issue by tezer** [tudarmstadt-lt/sensegram#9]
Senses and probabilities based on TWSI sense inventory are not found.

**Comment by alexanderpanchenko** [comment]
sorry, i can't find the files.

the original TWSI inventory it available here:
https://github.com/tudarmstadt-lt/context-eval/blob/master/data/Dataset-TWSI-2.csv
it is possible to reconstruct the files you mention by averaging
wiki/ukwac embeddings on the basis of this inventory

probabilities are simply proportional to the number of words in a sense
cluster (larger clusters have larger senses).

**Comment by tezer** [comment]
OK, thank you.

**Comment by alexanderpanchenko** [comment]
i asked my colleague -- still some chance we will get them, but it may take
time...

**Comment by tezer** [comment]
Thank you. That would be nice.
          
            
            On Jul 24 2017, at 7:37 pm, Alexander Panchenko <notifications@github.com> wrote:
            
            
              i asked my colleague -- still some chance we will get them, but it may take
time...

**Comment by alexanderpanchenko** [comment]
https://github.com/tudarmstadt-lt/context-eval/blob/master/data/Inventory-TWSI-2.csv

this file contains the twsi inventory in a more convenient format
